### PR TITLE
Expire values in Progressrus::Store::Redis

### PR DESCRIPTION
**Pull request by fw42**
Follow-up to https://github.com/Sirupsen/progressrus/pull/17.

Does this make sense?

@garymardell @Sirupsen

### CODE REVIEW

**Comment by Sirupsen** [comment]
Depends on @garymardell's use case, he added it.

**Comment by garymardell** [comment]
This works for me. The only concern from what I remember was having different progresses within a scope having different  expirations. But this doesn't affect my use case.

**Comment by Sirupsen** [comment]
In that case ship it.

**Comment by fw42** [comment]
Don't have merge permission :)

**Comment by fw42** [comment]
@Sirupsen merge?

**Pull request merged**
